# Input data
input_w: 512              
input_h: 512                 
age_min: 40                  
age_max: 200  
# Training hyperparameters                 
batch_size: 4              
epochs: 20    
# Optimizer parameters               
lr: 0.0001         
beta_1: 0.9                   
beta_2: 0.999
weight_decay: 0.0005  
# Learning rate scheduler                  
step_size: 10                
gamma: 0.1                                 
# Tensorboard log options
image_save_iter: 500      
image_log_iter: 500
log_iter: 5                  
# Loss weight
w:
  recon: 50
  class: 0.1
  adver: 1
  dis: 1
  gp: 1
  tv: 0
